# Select compose version
version: "3"

# Define services
services: 

    # Create matterbot service
    linbot:

        # Select service image
        build: linbot

        # Expose ports
        ports: 
            - 80:80

        # Mount volumes
        volumes:
            # Persistent data volume
            - data:/opt

            # Docker mount
            - /var/run/docker.sock:/var/run/docker.sock

        # Environment file
        env_file: 
            - ../environment.env

volumes:
    data: